context:
  test:
    test:
      sample: ${p:test.sample:${p:test.1:12345}}
      # sample: 12345678
      port: ${env:test.sample:${p:test.1:1200}}
      api-key: sample-key
      api-token: abcdefgf