application:
  name: DataFlow Application
  version: 1.0.1-beta

server:
  port: ${env:SERVER_PORT:8080}
  host: ${env:SERVER_HOST:0.0.0.0}
  
logging:
  level: ${env:LOG_LEVEL:INFO}
  config: conf/logback.yaml

database:
  host: "${env:DB_HOST:localhost}"
  port: "${env:DB_PORT:3306}"
  name: "${env:DB_NAME:app_db}"
  username: "${env:DB_USER:admin}"
  password: "${env:DB_PASSWORD:password}"

features:
  enabled: true
  api_url: "https://api.${server.host}:${server.port}/v1"

context:
  test:
    web:
      title: DataFlow
      root: ./
      num: 100
      types:
        - xls
        - xlsx
        - docs
        - doc
        - pdf